events { worker_connections 1024; }

http {
    server {
        listen 80;

        #API calls go to FastAPI
        server_tokens off;
        location /api/ {
            proxy_pass http://api:8000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        #everything else goes to the vite frontend
        location / {
            proxy_pass http://frontend:5173/; # i use this port for dev , for prod i should chnage it to 80
            add_header Cross-Origin-Opener-Policy "same-origin-allow-popups" always;
            
            proxy_set_header Host $host;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
}